version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPOSITORY_URI=381783421401.dkr.ecr.us-east-1.amazonaws.com/vijay
      - DOCKER_LOGIN_PASSWORD=$(aws ecr get-login-password  --region us-east-1)
      - docker login -u AWS -p $DOCKER_LOGIN_PASSWORD https://381783421401.dkr.ecr.us-east-1.amazonaws.com/vijay:latest
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t  $REPOSITORY_URI:awscpl-${CODEBUILD_BUILD_NUMBER} .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:awscpl-${CODEBUILD_BUILD_NUMBER}
      - echo writing image definitions file...
      - printf '[{"name":"awscpl","imageUri":"%s"}]' $REPOSITORY_URI:demo-app-${CODEBUILD_BUILD_NUMBER} > imagedefinitions.json
      - cat imagedefinitions.json 
      - pwd
artifacts:
    files: imagedefinitions.json
